package main

import (
	"bytes"
	"reflect"
	"testing"
)

func TestSplitLinkOnlyPackages(t *testing.T) {
	tests := []struct {
		name string
		list string
		want []string
	}{
		{name: "empty", list: "", want: nil},
		{name: "single", list: "libcore/coreentry", want: []string{"libcore/coreentry"}},
		{name: "multiple", list: "a/b,c/d", want: []string{"a/b", "c/d"}},
		{name: "spaces and empties", list: " a/b , ,c/d,", want: []string{"a/b", "c/d"}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got := splitLinkOnlyPackages(test.list)
			if !reflect.DeepEqual(got, test.want) {
				t.Errorf("splitLinkOnlyPackages(%q) = %v, want %v", test.list, got, test.want)
			}
		})
	}
}

func TestWriteLinkOnlyGo(t *testing.T) {
	var buf bytes.Buffer
	if err := writeLinkOnlyGo(&buf, []string{"libcore/coreentry", "example.com/other"}); err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by anjb. DO NOT EDIT.

// Packages listed with -linkonly are linked for their cgo //export
// symbols and init side effects; no bindings are generated for them.
package main

import (
	_ "libcore/coreentry"
	_ "example.com/other"
)
`
	if got := buf.String(); got != want {
		t.Errorf("writeLinkOnlyGo output mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}
